### ISSUE TITLE
Step 4- "Error has been found during the conversion !"

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-confluence-migrator#51]
Preconditions:

1. Install the Confluence Migrator on a local instance - ID: com.xwiki.confluence:application-confluence-migrator-ui, version:1.0-rc-9
2. Install the Pro Confluence Macros on the local instance
3. Access the Confluence Migrator in your Local instance and start a migration profile

Steps to reproduce:

1. Follow the Migration steps 1 to 4
2. At step 4 - Upload the Confluence file exported eg. 
[Confluence-export-space-qat.zip](https://github.com/xwikisas/application-confluence-migrator/files/7565927/Confluence-export-space-qat.zip)

Expected results: The file is uploaded.

Actual results:
Error has been found during the conversion !
```
fileSize' doesn't map to an existing object
class java.util.NoSuchElementException: 'fileSize' doesn't map to an existing object
    at org.apache.commons.configuration.AbstractConfiguration.getLong(AbstractConfiguration.java:862)
    at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readAttachment(ConfluenceInputFilterStream.java:866)
    at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readPageRevision(ConfluenceInputFilterStream.java:698)
    at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readPageRevision(ConfluenceInputFilterStream.java:559)
    at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readPage(ConfluenceInputFilterStream.java:452)
    at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readInternal(ConfluenceInputFilterStream.java:193)
    at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.read(ConfluenceInputFilterStream.java:138)
    at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.read(ConfluenceInputFilterStream.java:84)
    at org.xwiki.filter.input.AbstractBeanInputFilterStream.read(AbstractBeanInputFilterStream.java:79)
    at org.xwiki.filter.internal.job.FilterStreamConverterJob.runInternal(FilterStreamConverterJob.java:97)
    at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:243)
    at org.xwiki.job.AbstractJob.run(AbstractJob.java:220)
    at org.xwiki.filter.script.internal.ScriptFilterStreamConverterJob.run(ScriptFilterStreamConverterJob.java:75)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

![Error](https://user-images.githubusercontent.com/40691112/142494917-7be434ca-0fe1-40f4-a43c-99b406d01002.jpg)

![Error2](https://user-images.githubusercontent.com/40691112/142495502-1fb97133-965b-4627-b125-876c09bcd4f7.jpg)

Environments: Windows 10, XWiki 13.4.5 with MySQL 8.0 and Chrome 95, com.xwiki.confluence:application-confluence-migrator-ui version:1.0-rc-9

**Comment by acotiuga** [comment]
Reported and fixed in https://jira.xwiki.org/browse/CONFLUENCE-99 and upgraded the Confluence XML in ab2fa152c85f2140f22f83fc43e6b5cd8618aa2d.
