### ISSUE TITLE
Step 6 -  SQL error appears at Execution

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-confluence-migrator#54]
Steps to reproduce:

1. Follow the Confluence Migrator steps 1 to 4 using the [TEST space](https://xwikisas.atlassian.net/wiki/spaces/TEST/overview) 
2. Import the [TEST pages exported](https://up1.xwikisas.com/#RcSnPW3-Oq2ZFwiLPOdViQ)
3. Follow the other instructions till step 6
4. Click on "Compute plan" then "Execute plan"

Expected results: The Hierarchy from the TEST space is computed then executed.

Actual results: An SQL error appears at Execution.
![SQLError](https://user-images.githubusercontent.com/40691112/142633206-4dc819e0-80df-472c-bf80-fb42caae5876.jpg)

`SQL Error: 1406, SQLState: 22001
Data truncation: Data too long for column 'XWD_PARENT' at row 1
Failed to perform the migration of [xwiki:TEST.Too long Hierarchy\. Too long Hierarchy\. Too long Hierarchy 9].
com.xpn.xwiki.XWikiException: Error number 0 in 0: Error number 3201 in 3: Exception while saving document xwiki:TEST.Test.Test\. This is a test page.Long Hierarchy.Too long Hierarchy\. Too long Hierarchy\. Too long Hierarchy 1.Too long Hierarchy\. Too long Hierarchy\. Too long Hierarchy 2.Too long Hierarchy\. Too long Hierarchy\. Too long Hierarchy 3.Too long Hierarchy\. Too long Hierarchy\. Too long Hierarchy 4.Too long Hierarchy\. Too long Hierarchy\. Too long Hierarchy 5.Too long Hierarchy\. Too long Hierarchy\. Too long Hierarchy 6.Too long Hierarchy\. Too long Hierarchy\. Too long Hierarchy 7.Too long Hierarchy\. Too long Hierarchy\. Too long Hierarchy 8.Too long Hierarchy\. Too long Hierarchy\. Too long Hierarchy 9.WebHome
	at com.xpn.xwiki.store.XWikiHibernateStore.saveXWikiDoc(XWikiHibernateStore.java:729)
	at com.xpn.xwiki.store.XWikiCacheStore.saveXWikiDoc(XWikiCacheStore.java:257)
	at com.xpn.xwiki.store.XWikiCacheStore.saveXWikiDoc(XWikiCacheStore.java:217)
	at com.xpn.xwiki.XWiki.saveDocument(XWiki.java:2052)
	at com.xpn.xwiki.doc.DefaultDocumentAccessBridge.saveDocument(DefaultDocumentAccessBridge.java:994)
	at com.xpn.xwiki.doc.DefaultDocumentAccessBridge.setDocumentParentReference(DefaultDocumentAccessBridge.java:326)
	at org.xwiki.contrib.nestedpagesmigrator.internal.executor.MigrationPlanExecutor.moveDocument(MigrationPlanExecutor.java:227)
	at org.xwiki.contrib.nestedpagesmigrator.internal.executor.MigrationPlanExecutor.performAction(MigrationPlanExecutor.java:139)
	at org.xwiki.contrib.nestedpagesmigrator.internal.executor.MigrationPlanExecutor.performAction(MigrationPlanExecutor.java:153)
	at org.xwiki.contrib.nestedpagesmigrator.internal.executor.MigrationPlanExecutor.performAction(MigrationPlanExecutor.java:153)
	at org.xwiki.contrib.nestedpagesmigrator.internal.executor.MigrationPlanExecutor.performAction(MigrationPlanExecutor.java:153)
	at org.xwiki.contrib.nestedpagesmigrator.internal.executor.MigrationPlanExecutor.performAction(MigrationPlanExecutor.java:153)
	at org.xwiki.contrib.nestedpagesmigrator.internal.executor.MigrationPlanExecutor.performAction(MigrationPlanExecutor.java:153)
	at org.xwiki.contrib.nestedpagesmigrator.internal.executor.MigrationPlanExecutor.performAction(MigrationPlanExecutor.java:153)
	at org.xwiki.contrib.nestedpagesmigrator.internal.executor.MigrationPlanExecutor.performAction(MigrationPlanExecutor.java:153)
	at org.xwiki.contrib.nestedpagesmigrator.internal.executor.MigrationPlanExecutor.performAction(MigrationPlanExecutor.java:153)
	at org.xwiki.contrib.nestedpagesmigrator.internal.executor.MigrationPlanExecutor.performAction(MigrationPlanExecutor.java:153)
	at org.xwiki.contrib.nestedpagesmigrator.internal.executor.MigrationPlanExecutor.performAction(MigrationPlanExecutor.java:153)
	at org.xwiki.contrib.nestedpagesmigrator.internal.executor.MigrationPlanExecutor.performAction(MigrationPlanExecutor.java:153)
	at org.xwiki.contrib.nestedpagesmigrator.internal.executor.MigrationPlanExecutor.performAction(MigrationPlanExecutor.java:153)
	at org.xwiki.contrib.nestedpagesmigrator.internal.executor.MigrationPlanExecutor.performMigration(MigrationPlanExecutor.java:110)
	at org.xwiki.contrib.nestedpagesmigrator.internal.job.MigrationPlanExecutorJob.runInternal(MigrationPlanExecutorJob.java:58)
	at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:243)
	at org.xwiki.job.AbstractJob.run(AbstractJob.java:220)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.DataException: could not execute statement
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1366)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:453)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3212)
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2380)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:448)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
	at com.xpn.xwiki.internal.store.hibernate.HibernateStore.endTransaction(HibernateStore.java:848)
	at com.xpn.xwiki.store.XWikiHibernateBaseStore.endTransaction(XWikiHibernateBaseStore.java:603)
	at com.xpn.xwiki.store.XWikiHibernateStore.saveXWikiDoc(XWikiHibernateStore.java:720)
	... 26 more
Caused by: org.hibernate.exception.DataException: could not execute statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:52)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3492)
	at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3354)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3768)
	at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:201)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
	at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
	at java.util.LinkedHashMap.forEach(Unknown Source)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:345)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:93)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1362)
	... 37 more
Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'XWD_PARENT' at row 1: null
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
	... 49 more`

Environments: Windows 10, XWiki 13.4.5 with MySQL 8.0 and Chrome 95, com.xwiki.confluence:application-confluence-migrator-ui version:1.0-rc-10

**Comment by acotiuga** [comment]
This is caused by a platform bug: https://jira.xwiki.org/browse/XWIKI-19207 and there is nothing we can do in the Confluence migrator. 
In addition, the document is properly created only the parent value is truncated in the database, so this is not a blocker at all. 
Then, this happens on very very long hierarchies which I would like to consider that are not the regular cases but rather some exceptions.
