### ISSUE TITLE
Step 4 throw NoSuchMethodError Exception

### ISSUE THREAD

**Issue by Glarme** [xwikisas/application-confluence-migrator#71]
# Base Info 

 - XWIKI Version: 14.5
 - Confluence Migrator Version: 1.0.6

## Confluence Migrator Dependencies

 - Confluence Migrator Application - API:  1.0.6
 - Confluence XML: 9.14.4
 - Filter Streams Converter Application: 12.10
 - Nested Pages Migrator Application: 0.7.3
 - Pro Macros: 1.2.1
 - smartwizard: 5.1.1
 - Job Macro: 2.0
 - Office Importer Application: 12.10
 - Event Listeners Administration: 1.0.2
 
 
# Question
 
## Desc

Step 4 throw `NoSuchMethodError` exception

## Exception Stack:
	'void org.xwiki.rendering.internal.parser.wikimodel.WikiModelParserUtils.parseInline(org.xwiki.rendering.parser.StreamParser, java.lang.String, org.xwiki.rendering.listener.Listener, boolean)'
    class java.lang.NoSuchMethodError: 'void org.xwiki.rendering.internal.parser.wikimodel.WikiModelParserUtils.parseInline(org.xwiki.rendering.parser.StreamParser, java.lang.String, org.xwiki.rendering.listener.Listener, boolean)'
        at org.xwiki.contrib.confluence.parser.xhtml.internal.wikimodel.ConfluenceXWikiGeneratorListener.onReference(ConfluenceXWikiGeneratorListener.java:180)
        at org.xwiki.rendering.wikimodel.impl.InternalWikiScannerContext.onReference(InternalWikiScannerContext.java:1093)
        at org.xwiki.rendering.wikimodel.impl.WikiScannerContext.onReference(WikiScannerContext.java:621)
        at org.xwiki.contrib.confluence.parser.xhtml.internal.wikimodel.LinkTagHandler.end(LinkTagHandler.java:87)
        at org.xwiki.rendering.wikimodel.xhtml.handler.TagHandler.endElement(TagHandler.java:85)
        at org.xwiki.rendering.wikimodel.xhtml.impl.TagContext.endElement(TagContext.java:81)
        at org.xwiki.rendering.wikimodel.xhtml.impl.TagStack.endElement(TagStack.java:123)
        at org.xwiki.rendering.wikimodel.xhtml.impl.XhtmlHandler.endElement(XhtmlHandler.java:196)
        at java.xml/org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
        at org.xwiki.rendering.wikimodel.xhtml.filter.XHTMLWhitespaceXMLFilter.sendInlineEvent(XHTMLWhitespaceXMLFilter.java:302)
        at org.xwiki.rendering.wikimodel.xhtml.filter.XHTMLWhitespaceXMLFilter.sendPreviousContent(XHTMLWhitespaceXMLFilter.java:291)
        at org.xwiki.rendering.wikimodel.xhtml.filter.XHTMLWhitespaceXMLFilter.flushContent(XHTMLWhitespaceXMLFilter.java:332)
        at org.xwiki.rendering.wikimodel.xhtml.filter.XHTMLWhitespaceXMLFilter.flushContent(XHTMLWhitespaceXMLFilter.java:314)
        at org.xwiki.rendering.wikimodel.xhtml.filter.XHTMLWhitespaceXMLFilter.endElement(XHTMLWhitespaceXMLFilter.java:183)
        at org.xwiki.contrib.confluence.parser.xhtml.internal.wikimodel.ConfluenceXHTMLWhitespaceXMLFilter.endElement(ConfluenceXHTMLWhitespaceXMLFilter.java:90)
        at java.xml/org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
        at org.xwiki.rendering.wikimodel.xhtml.filter.AccumulationXMLFilter.endElement(AccumulationXMLFilter.java:86)
        at java.xml/org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
        at org.xwiki.rendering.wikimodel.xhtml.filter.DTDXMLFilter.endElement(DTDXMLFilter.java:86)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLDTDValidator.endNamespaceScope(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLDTDValidator.handleEndElement(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLDTDValidator.endElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at java.xml/org.xml.sax.helpers.XMLFilterImpl.parse(XMLFilterImpl.java:357)
        at org.xwiki.rendering.wikimodel.xhtml.filter.DefaultXMLFilter.parse(DefaultXMLFilter.java:58)
        at java.xml/org.xml.sax.helpers.XMLFilterImpl.parse(XMLFilterImpl.java:357)
        at org.xwiki.rendering.wikimodel.xhtml.filter.DefaultXMLFilter.parse(DefaultXMLFilter.java:58)
        at java.xml/org.xml.sax.helpers.XMLFilterImpl.parse(XMLFilterImpl.java:357)
        at org.xwiki.rendering.wikimodel.xhtml.filter.DefaultXMLFilter.parse(DefaultXMLFilter.java:58)
        at org.xwiki.rendering.wikimodel.xhtml.XhtmlParser.parse(XhtmlParser.java:134)
        at org.xwiki.rendering.internal.parser.wikimodel.AbstractWikiModelParser.parse(AbstractWikiModelParser.java:134)
        at org.xwiki.contrib.confluence.parser.xhtml.internal.ConfluenceXHTMLParser.parse(ConfluenceXHTMLParser.java:246)
        at org.xwiki.rendering.internal.parser.wikimodel.AbstractWikiModelParser.parse(AbstractWikiModelParser.java:114)
        at org.xwiki.contrib.confluence.parser.xhtml.internal.ConfluenceXHTMLInputFilterStream.read(ConfluenceXHTMLInputFilterStream.java:115)
        at org.xwiki.contrib.confluence.parser.xhtml.internal.ConfluenceXHTMLInputFilterStream.read(ConfluenceXHTMLInputFilterStream.java:47)
        at org.xwiki.filter.input.AbstractBeanInputFilterStream.read(AbstractBeanInputFilterStream.java:79)
        at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.parse(ConfluenceInputFilterStream.java:817)
        at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.convertToXWiki21(ConfluenceInputFilterStream.java:786)
        at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readPageRevision(ConfluenceInputFilterStream.java:644)
        at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readPageRevision(ConfluenceInputFilterStream.java:559)
        at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readPage(ConfluenceInputFilterStream.java:447)
        at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readInternal(ConfluenceInputFilterStream.java:202)
        at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.read(ConfluenceInputFilterStream.java:138)
        at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.read(ConfluenceInputFilterStream.java:84)
        at org.xwiki.filter.input.AbstractBeanInputFilterStream.read(AbstractBeanInputFilterStream.java:79)
        at org.xwiki.filter.internal.job.FilterStreamConverterJob.runInternal(FilterStreamConverterJob.java:97)
        at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:243)
        at org.xwiki.job.AbstractJob.run(AbstractJob.java:220)
        at org.xwiki.filter.script.internal.ScriptFilterStreamConverterJob.run(ScriptFilterStreamConverterJob.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
		
## Screenshot
 
![XWIKI-Migrator-Exception](https://user-images.githubusercontent.com/12939593/185358048-31ead1ea-3551-4cec-a7d0-f6e7c46f6668.png)

**Comment by acotiuga** [comment]
@Glarme thanks for reporting this problem. It is also known as #70 and the need here is to upgrade the dependency to the latest version. Upgrading Confluence XML to 9.14.5 would solve your problem.

**Comment by Glarme** [comment]
> @Glarme thanks for reporting this problem. It is also known as #70 and the need here is to upgrade the dependency to the latest version. Upgrading Confluence XML to 9.14.5 would solve your problem.

Yeah, thanks bro, I have upgraded to 9.15.0, which solved this problem; the import process can be completed, but an exception will be thrown when some pages are imported and parsed, although the files of these paths actually exist, may this affect the import data?

 

> /data/xwiki/apache-tomcat-9.0.64/work/Catalina/localhost/xwiki/store/file/xwiki/0/6/77ef0a1e852c9be2a7d23b89d51c06/attachments/2/6/058b569116cb5b281769d8e096e551/fv1.2.png (No such file or directory)
class org.xwiki.store.UnexpectedException: Failed to get InputStream
    at org.xwiki.store.legacy.doc.internal.FilesystemAttachmentContent.getContentInputStream(FilesystemAttachmentContent.java:127)
    at com.xpn.xwiki.doc.XWikiAttachment.getContentInputStream(XWikiAttachment.java:924)
    at com.xpn.xwiki.doc.XWikiAttachment.getContentInputStream(XWikiAttachment.java:919)
    at com.xpn.xwiki.doc.XWikiDocument.retrieveDeletedAttachment(XWikiDocument.java:7157)
    at com.xpn.xwiki.doc.XWikiDocument.getAttachmentDiff(XWikiDocument.java:7121)
    at com.xpn.xwiki.internal.event.AttachmentEventGeneratorListener.onDocumentUpdatedEvent(AttachmentEventGeneratorListener.java:139)
    at com.xpn.xwiki.internal.event.AttachmentEventGeneratorListener.onEvent(AttachmentEventGeneratorListener.java:88)
    at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:320)
    at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:285)
    at com.xpn.xwiki.XWiki.afterSave(XWiki.java:2015)
    at com.xpn.xwiki.XWiki.saveDocument(XWiki.java:2093)
    at com.xpn.xwiki.internal.filter.output.DocumentInstanceOutputFilterStream.maybeSaveDocument(DocumentInstanceOutputFilterStream.java:258)
    at com.xpn.xwiki.internal.filter.output.DocumentInstanceOutputFilterStream.endWikiDocumentRevision(DocumentInstanceOutputFilterStream.java:170)
    at jdk.internal.reflect.GeneratedMethodAccessor116.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.xwiki.filter.internal.FilterProxy.invoke(FilterProxy.java:90)
    at org.xwiki.filter.internal.CompositeFilter.invoke(CompositeFilter.java:75)
    at com.sun.proxy.$Proxy168.endWikiDocumentRevision(Unknown Source)
    at jdk.internal.reflect.GeneratedMethodAccessor116.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.xwiki.filter.internal.FilterProxy.invoke(FilterProxy.java:90)
    at org.xwiki.filter.internal.CompositeFilter.invoke(CompositeFilter.java:75)
    at com.sun.proxy.$Proxy169.endWikiDocumentRevision(Unknown Source)
    at jdk.internal.reflect.GeneratedMethodAccessor116.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.xwiki.filter.internal.FilterProxy.invoke(FilterProxy.java:90)
    at org.xwiki.filter.internal.FilterProxy.invoke(FilterProxy.java:63)
    at com.sun.proxy.$Proxy170.endWikiDocumentRevision(Unknown Source)
    at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readPageRevision(ConfluenceInputFilterStream.java:761)
    at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readPageRevision(ConfluenceInputFilterStream.java:573)
    at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readPage(ConfluenceInputFilterStream.java:461)
    at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readInternal(ConfluenceInputFilterStream.java:211)
    at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.read(ConfluenceInputFilterStream.java:141)
    at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.read(ConfluenceInputFilterStream.java:84)
    at org.xwiki.filter.input.AbstractBeanInputFilterStream.read(AbstractBeanInputFilterStream.java:79)
    at org.xwiki.filter.internal.job.FilterStreamConverterJob.runInternal(FilterStreamConverterJob.java:97)
    at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:243)
    at org.xwiki.job.AbstractJob.run(AbstractJob.java:220)
    at org.xwiki.filter.script.internal.ScriptFilterStreamConverterJob.run(ScriptFilterStreamConverterJob.java:75)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: class java.io.FileNotFoundException: /data/xwiki/apache-tomcat-9.0.64/work/Catalina/localhost/xwiki/store/file/xwiki/0/6/77ef0a1e852c9be2a7d23b89d51c06/attachments/2/6/058b569116cb5b281769d8e096e551/fv1.2.png (No such file or directory)
    at java.base/java.io.FileInputStream.open0(Native Method)
    at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
    at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
    at org.xwiki.store.legacy.doc.internal.FilesystemAttachmentContent.getContentInputStream(FilesystemAttachmentContent.java:125)
    at com.xpn.xwiki.doc.XWikiAttachment.getContentInputStream(XWikiAttachment.java:924)
    at com.xpn.xwiki.doc.XWikiAttachment.getContentInputStream(XWikiAttachment.java:919)
    at com.xpn.xwiki.doc.XWikiDocument.retrieveDeletedAttachment(XWikiDocument.java:7157)
    at com.xpn.xwiki.doc.XWikiDocument.getAttachmentDiff(XWikiDocument.java:7121)
    at com.xpn.xwiki.internal.event.AttachmentEventGeneratorListener.onDocumentUpdatedEvent(AttachmentEventGeneratorListener.java:139)
    at com.xpn.xwiki.internal.event.AttachmentEventGeneratorListener.onEvent(AttachmentEventGeneratorListener.java:88)
    at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:320)
    at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:285)
    at com.xpn.xwiki.XWiki.afterSave(XWiki.java:2015)
    at com.xpn.xwiki.XWiki.saveDocument(XWiki.java:2093)
    at com.xpn.xwiki.internal.filter.output.DocumentInstanceOutputFilterStream.maybeSaveDocument(DocumentInstanceOutputFilterStream.java:258)
    at com.xpn.xwiki.internal.filter.output.DocumentInstanceOutputFilterStream.endWikiDocumentRevision(DocumentInstanceOutputFilterStream.java:170)
    at jdk.internal.reflect.GeneratedMethodAccessor116.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.xwiki.filter.internal.FilterProxy.invoke(FilterProxy.java:90)
    at org.xwiki.filter.internal.CompositeFilter.invoke(CompositeFilter.java:75)
    at com.sun.proxy.$Proxy168.endWikiDocumentRevision(Unknown Source)
    at jdk.internal.reflect.GeneratedMethodAccessor116.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.xwiki.filter.internal.FilterProxy.invoke(FilterProxy.java:90)
    at org.xwiki.filter.internal.CompositeFilter.invoke(CompositeFilter.java:75)
    at com.sun.proxy.$Proxy169.endWikiDocumentRevision(Unknown Source)
    at jdk.internal.reflect.GeneratedMethodAccessor116.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.xwiki.filter.internal.FilterProxy.invoke(FilterProxy.java:90)
    at org.xwiki.filter.internal.FilterProxy.invoke(FilterProxy.java:63)
    at com.sun.proxy.$Proxy170.endWikiDocumentRevision(Unknown Source)
    at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readPageRevision(ConfluenceInputFilterStream.java:761)
    at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readPageRevision(ConfluenceInputFilterStream.java:573)
    at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readPage(ConfluenceInputFilterStream.java:461)
    at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readInternal(ConfluenceInputFilterStream.java:211)
    at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.read(ConfluenceInputFilterStream.java:141)
    at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.read(ConfluenceInputFilterStream.java:84)
    at org.xwiki.filter.input.AbstractBeanInputFilterStream.read(AbstractBeanInputFilterStream.java:79)
    at org.xwiki.filter.internal.job.FilterStreamConverterJob.runInternal(FilterStreamConverterJob.java:97)
    at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:243)
    at org.xwiki.job.AbstractJob.run(AbstractJob.java:220)
    at org.xwiki.filter.script.internal.ScriptFilterStreamConverterJob.run(ScriptFilterStreamConverterJob.java:75)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Glarme** [comment]
Can this migration tool maintain the tree-like directory structure between pages similar to Confluence? Now that over 500 pages have been imported, they are all expanded. Is there something I missed in the configuration?

**Comment by acotiuga** [comment]
It looks like something went wrong with the Nested Spaces Migration, on step 6. See https://store.xwiki.com/xwiki/bin/view/Extension/Confluence%20Migrator/#HStep6

**Comment by Glarme** [comment]
@acotiuga It should be that I did not perform the "With hierarchy analysis" check in Step2, so that Step6 failed to repair the data structure. The reason I ignored this check was that an error was reported when importing Test Space before, and it seemed to have no effect on the result of the import, but now It seems that it should affect the hierarchical structure of the page. Can you help me find the reason? 

Screenshot:
![1](https://user-images.githubusercontent.com/12939593/185381073-f9ac49bb-d04c-4e14-ad9d-f1510bc73644.png)
![2](https://user-images.githubusercontent.com/12939593/185381109-07f7789e-a35f-41a6-9891-3ed549f5a6cf.png)

**Comment by acotiuga** [comment]
This issue duplicates #70, so it can be closed.
